### ISSUE TITLE
[Feature] 等一个Python版本

### ISSUE THREAD

**Issue by Chrisma-98** [oddfar/coze-discord#4]
## 例行检查

+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

## 功能请求

后期会有其他语言吗？比如python版本的

## 解决方案和应用场景

融入现有的大语言模型测试框架

**Comment by oddfar** [comment]
不熟悉python，不考虑写个新版本
